--- 
abstract: The Object Oriented English.pm
author: 
  - Ask Solem <asksh@cpan.org>
build_requires: 
  Test::Exception: 0.22
  Test::Simple: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: bsd
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: sys
no_index: 
  directory: 
    - examples
    - devel
    - inc
    - t
requires: 
  Class::Dot: 2
  perl: 5.6.0
  version: 0
tests: t/*.t t/*/*.t t/*/*/*.t
version: 0.2
